Adding another useful script * Added a `protodoc` script that runs `protoc` with the `protoc-gen-doc` plugin assumed to be installed in `~/go/bin`.    * Also added a modified markdown template the script uses to avoid `html` filtering, so the output of PBJ can be (mostly) usable javadoc and the markdown can work better for fields.       * The markdown process removes all newlines within the single-field table cell, so fields should use `html` markup, such as `<ul>`, `<p>`, `<br/>`, `<sup>`, etc... * Updated `verify-protos` to pass `no-daemon` so it doesn't start or use a gradle daemon, which can cause "sticky" file issues.

diff --git a/verify-protos b/verify-protos
--- a/verify-protos
+++ b/verify-protos
@@ -22,7 +22,7 @@ else
   if [[ ! -f ${backupFileName} ]]
   then
     ${ECHO} sed -i "${backupExtension}" -e 's/val hapiProtoBranchOrTag = "\(.*\)"/val hapiProtoBranchOrTag = "'"${branchToVerify}"'"/' "${settingsFile}"
-    (${ECHO} ./gradlew clean "${gradleBuildTask}" --no-build-cache --no-configuration-cache) || (echo;echo;echo `FAILED`;echo;echo)
+    (${ECHO} ./gradlew clean "${gradleBuildTask}" --no-daemon --no-build-cache --no-configuration-cache) || (echo;echo;echo `FAILED`;echo;echo)
     if [[ -f ${backupFileName} ]]
     then
       ${ECHO} rm "${settingsFile}"
